---
title: ７セグ時計ICを自作する本
subtitle: Chevron7 *Locked*
circle: KY技研
author: "@_K4ZUKI_"
comiket: 技術書典７
year: 2019
publisher: キンコーズオンラインで印刷製本秋葉原店で受け取り
docrevision: "1.0"
front: "`svg/MilkyWay_Stargate_blank.pdf`{=latex}"
verbcolored: false
rmnote: true

frontoption:
  - scale=1.8
  - position=current page.south
  - angle=0

svgbob:
  font-family: "Source Code Pro"
  font-size: 14
  scale: 1
  strike-width: 2

heading-unnumbered:
  1: "Heading Unnumbered 1"
  2: "Heading Unnumbered 2"
  3: "Heading Unnumbered 3"
  4: "Heading Unnumbered 4"

bullet-style:
  1: "Bullet List 1"
  2: "Bullet List 2"
  3: "Bullet List 3"

numbered-bullets:
  1: "Number Bullet"
  2: "Number Bullet 2"
  3: "Number Bullet 3"

image-div-style: "Image Caption"

docx_coreprop:
  #  author: "K4ZUKI" # str
  #  category: "Category" # str
  #  comments: "Comment" # str
  #  keywords: "Keyword1 Keyword2" # str
  #  last_modified_by: "K4ZUKI" # str
  #  last_printed: "31-Dec-2018" # datetime DD-MMM-YYYY
  #  modified: "31-Dec-2018" # datetime DD-MMM-YYYY
  #  revision: 1123 # int < 32768
  #  subject: "SubjecT" # str
  #  title: "Title" # str

  #  created: "31-Dec-2018" # datetime DD-MMM-YYYY set externally
  #  content_status: "Status" # ignored?
  #  identifier: "ID" # ignored?
  #  language: "Japanese" # ignored?
  #  version: "Version" # ignored?

  table-alignment-in-page: center # left / center /right
  table-cell-vertical-alignment: center # top / center / bottom / both
  #  read-only-recommended: true
  disable-table-autofit: true # setting 'true' requires explicit column widths setting
  table:
    "Normal Table": "Centered"
  paragraph:
    "Image Caption": "Figure Caption"
    "Normal": "Body Text"
    "First Paragraph": "Body Text"
  character:
    "Verbatim Char": "NormalTok"
...
